CREATE TABLE roles (role_id BIGINT AUTO_INCREMENT PRIMARY KEY, role_name VARCHAR(50) UNIQUE NOT NULL);
CREATE TABLE users (user_id BIGINT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(100) NOT NULL,email VARCHAR(100) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role_id BIGINT NOT NULL,active BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_user_role FOREIGN KEY(role_id) REFERENCES roles(role_id),INDEX idx_users_email(email),INDEX idx_users_role(role_id));
CREATE TABLE vendors (vendor_id BIGINT AUTO_INCREMENT PRIMARY KEY,vendor_code VARCHAR(20) UNIQUE NOT NULL,vendor_name VARCHAR(200) NOT NULL,category VARCHAR(50),contact_email VARCHAR(100),phone VARCHAR(20),country VARCHAR(50),status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',owner_user_id BIGINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_user_id) REFERENCES users(user_id) ON DELETE SET NULL,INDEX idx_vendor_status(status),INDEX idx_vendor_category(category));
CREATE TABLE departments (department_id BIGINT AUTO_INCREMENT PRIMARY KEY,department_name VARCHAR(100) NOT NULL,manager_name VARCHAR(100),INDEX idx_department_name(department_name));
CREATE TABLE vendor_departments(vendor_id BIGINT NOT NULL,department_id BIGINT NOT NULL,assigned_date DATE NOT NULL,PRIMARY KEY(vendor_id,department_id),FOREIGN KEY(vendor_id) REFERENCES vendors(vendor_id) ON DELETE CASCADE,FOREIGN KEY(department_id) REFERENCES departments(department_id) ON DELETE CASCADE);
CREATE TABLE contracts(contract_id BIGINT AUTO_INCREMENT PRIMARY KEY,contract_number VARCHAR(50) UNIQUE NOT NULL,vendor_id BIGINT NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,contract_value DECIMAL(15,2) NOT NULL,payment_frequency VARCHAR(20),status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',renewal_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(vendor_id) REFERENCES vendors(vendor_id) ON DELETE CASCADE,CONSTRAINT ck_contract_dates CHECK(end_date>start_date),INDEX idx_contract_status(status),INDEX idx_contract_end_date(end_date));
CREATE TABLE audit_logs(audit_id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT,action VARCHAR(50) NOT NULL,entity_name VARCHAR(50) NOT NULL,entity_id BIGINT NOT NULL,old_value TEXT,new_value TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE SET NULL,INDEX idx_audit_entity(entity_name),INDEX idx_audit_created(created_at));
INSERT INTO roles(role_name) VALUES ('ADMIN'),('MANAGER'),('VIEWER');
INSERT INTO users(full_name,email,password_hash,role_id) VALUES ('Admin User','admin@vms.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',1),('Manager User','manager@vms.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',2),('Viewer User','viewer@vms.com','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',3);
