'use client'

import { useMemo, useState } from 'react'
import {
  AlertCircle, ArrowDownRight, ArrowLeft, ArrowUpRight, BarChart3, Bell, Building2,
  CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, ClipboardList, Copy,
  Download, Eye, FileCheck2, FileText, Filter, Home, LayoutDashboard, LogOut, Mail,
  Menu, MoreHorizontal, Pencil, Plus, Search, Settings, ShieldCheck, Sparkles, Trash2,
  TrendingUp, UserRound, Users, X, XCircle
} from 'lucide-react'

const vendors = [
  { code:'VND-1042', name:'Tata Consultancy Services', category:'Technology', email:'procurement@tcs.com', country:'India', status:'Active', owner:'Priya Menon', contracts:12, value:4820000 },
  { code:'VND-1088', name:'BlueDart Express', category:'Logistics', email:'accounts@bluedart.com', country:'India', status:'Active', owner:'Rohan Shah', contracts:7, value:1260000 },
  { code:'VND-1106', name:'Deloitte India', category:'Consulting', email:'vendor.support@deloitte.com', country:'India', status:'Active', owner:'Ananya Rao', contracts:5, value:2340000 },
  { code:'VND-1134', name:'Hindustan Unilever', category:'Facilities', email:'partners@hul.com', country:'India', status:'Inactive', owner:'Vikram Singh', contracts:3, value:840000 },
  { code:'VND-1172', name:'Freshworks', category:'Software', email:'billing@freshworks.com', country:'India', status:'Active', owner:'Priya Menon', contracts:4, value:910000 },
  { code:'VND-1193', name:'TeamLease Services', category:'Staffing', email:'enterprise@teamlease.com', country:'India', status:'Active', owner:'Rohan Shah', contracts:8, value:1780000 },
]
const contracts = [
  { id:'CNT-2026-084', vendor:'Tata Consultancy Services', value:1240000, start:'01 Jan 2026', end:'28 Aug 2026', days:20, status:'Active', priority:'High', freq:'Quarterly', renewal:'Auto-renew' },
  { id:'CNT-2026-077', vendor:'BlueDart Express', value:385000, start:'15 Feb 2026', end:'12 Sep 2026', days:35, status:'Active', priority:'Medium', freq:'Monthly', renewal:'Review' },
  { id:'CNT-2026-061', vendor:'Deloitte India', value:820000, start:'01 Apr 2026', end:'30 Nov 2026', days:114, status:'Active', priority:'Low', freq:'Yearly', renewal:'Auto-renew' },
  { id:'CNT-2025-198', vendor:'Hindustan Unilever', value:510000, start:'01 Jan 2025', end:'31 Jul 2026', days:-8, status:'Expired', priority:'Medium', freq:'Monthly', renewal:'Expired' },
  { id:'CNT-2026-091', vendor:'Freshworks', value:275000, start:'12 May 2026', end:'11 Dec 2026', days:125, status:'Draft', priority:'Low', freq:'Yearly', renewal:'Pending' },
]
const initials=(name:string)=>name.split(' ').map(x=>x[0]).slice(0,2).join('')
const money=(n:number)=>'₹'+n.toLocaleString('en-IN')

type View='dashboard'|'vendors'|'vendor'|'contracts'|'reports'|'settings'|'login'

export default function Page(){
  const [view,setView]=useState<View>('dashboard'); const [selectedVendor,setSelectedVendor]=useState(vendors[0]); const [mobileOpen,setMobileOpen]=useState(false); const [query,setQuery]=useState(''); const [logged,setLogged]=useState(true)
  if(!logged) return <Login onLogin={()=>setLogged(true)}/>
  const go=(next:View)=>{setView(next);setMobileOpen(false)}
  return <div className="app-shell">
    <Sidebar view={view} go={go} mobileOpen={mobileOpen} close={()=>setMobileOpen(false)} logout={()=>setLogged(false)}/>
    <div className="app-main"><header className="topbar"><button className="icon-btn mobile-menu" aria-label="Open menu" onClick={()=>setMobileOpen(true)}><Menu/></button><div className="crumb"><Home size={14}/><span>Workspace</span><ChevronRight size={13}/><b>{view==='vendor'?'Vendor detail':view[0].toUpperCase()+view.slice(1)}</b></div><div className="top-actions"><label className="global-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything"/><kbd>⌘ K</kbd></label><button className="icon-btn" aria-label="Notifications"><Bell/><i/></button><button className="profile-mini" onClick={()=>go('login')}><span className="avatar avatar-blue">PM</span><span className="profile-copy"><b>Priya Menon</b><small>Procurement lead</small></span><ChevronDown size={15}/></button></div></header><main className="content">{view==='dashboard'&&<Dashboard go={go}/>} {view==='vendors'&&<Vendors go={go} select={(v:any)=>{setSelectedVendor(v);go('vendor')}}/>} {view==='vendor'&&<VendorDetail vendor={selectedVendor} back={()=>go('vendors')}/>} {view==='contracts'&&<Contracts/>} {view==='reports'&&<Reports/>} {view==='settings'&&<SettingsPage/>}</main></div>
  </div>
}

function Brand(){return <div className="brand"><span className="brand-mark"><ShieldCheck size={19}/></span><span>Vendor<span>Flow</span></span></div>}
function Sidebar({view,go,mobileOpen,close,logout}:{view:View;go:(v:View)=>void;mobileOpen:boolean;close:()=>void;logout:()=>void}){return <><aside className={`sidebar ${mobileOpen?'open':''}`}><div className="sidebar-top"><Brand/><button className="icon-btn close-menu" onClick={close}><X/></button></div><div className="workspace-switch"><span className="workspace-dot"/><div><b>Acme Industries</b><small>Enterprise workspace</small></div><ChevronDown size={14}/></div><nav><p className="nav-label">Workspace</p><Nav icon={LayoutDashboard} label="Dashboard" active={view==='dashboard'} click={()=>go('dashboard')}/><Nav icon={Users} label="Vendors" active={view==='vendors'||view==='vendor'} click={()=>go('vendors')}/><Nav icon={FileText} label="Contracts" active={view==='contracts'} click={()=>go('contracts')} count="24"/><Nav icon={BarChart3} label="Reports" active={view==='reports'} click={()=>go('reports')}/><p className="nav-label nav-gap">Manage</p><Nav icon={Settings} label="Settings" active={view==='settings'} click={()=>go('settings')}/><Nav icon={ClipboardList} label="Activity log"/></nav><div className="sidebar-bottom"><div className="help-card"><Sparkles size={16}/><div><b>Need a hand?</b><small>Visit the help center</small></div><ChevronRight size={14}/></div><div className="user-row"><span className="avatar avatar-blue">PM</span><div><b>Priya Menon</b><small>Admin</small></div><button className="icon-btn" onClick={logout} aria-label="Log out"><LogOut/></button></div></div></aside>{mobileOpen&&<div className="scrim" onClick={close}/>}</>}
function Nav({icon:Icon,label,active,click,count}:{icon:any;label:string;active?:boolean;click?:()=>void;count?:string}){return <button className={`nav-item ${active?'active':''}`} onClick={click}><Icon/><span>{label}</span>{count&&<em>{count}</em>}</button>}
function PageHead({eyebrow,title,sub,action}:{eyebrow?:string;title:string;sub:string;action?:React.ReactNode}){return <div className="page-head"><div><p className="eyebrow">{eyebrow||'Overview'}</p><h1>{title}</h1><p className="subtext">{sub}</p></div>{action}</div>}
function Stat({icon:Icon,label,value,trend,kind='blue'}:{icon:any;label:string;value:string;trend:string;kind?:string}){return <article className="stat-card"><div className={`stat-icon ${kind}`}><Icon/></div><div className="stat-meta"><span>{label}</span><strong>{value}</strong><small className={trend.startsWith('-')?'negative':''}>{trend.startsWith('-')?<ArrowDownRight/>:<ArrowUpRight/>}{trend.replace('-','')} <i>vs last month</i></small></div><MoreHorizontal className="stat-more"/></article>}
function Dashboard({go}:{go:(v:View)=>void}){return <><PageHead eyebrow="Monday, 24 August 2026" title="Good morning, Priya" sub="Here is what is happening across your vendor portfolio today." action={<button className="button primary" onClick={()=>go('contracts')}><Plus/>New contract</button>}/><section className="stats-grid"><Stat icon={Building2} label="Active vendors" value="128" trend="12.4%"/><Stat icon={FileCheck2} label="Total contracts" value="246" trend="8.2%" kind="violet"/><Stat icon={TrendingUp} label="Contract value" value="₹18,50,000" trend="14.8%" kind="green"/><Stat icon={AlertCircle} label="Expiring in 30 days" value="18" trend="-4.6%" kind="amber"/><Stat icon={XCircle} label="Expired contracts" value="7" trend="-18.2%" kind="red"/></section><section className="dashboard-grid"><article className="card chart-card wide"><CardTitle title="Vendor distribution" sub="Active vendors by category" action={<button className="select-btn">This year <ChevronDown/></button>}/><div className="bar-chart"><div className="y-axis"><span>50</span><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="bars">{[['Technology',44,'#2563eb'],['Logistics',31,'#60a5fa'],['Consulting',38,'#818cf8'],['Facilities',24,'#a5b4fc'],['Staffing',29,'#c4b5fd'],['Software',35,'#38bdf8']].map(([name,h,c]:any)=><div className="bar-col" key={name}><div className="bar-value">{h}</div><div className="bar" style={{height:`${h*3.1}px`,background:c}}/><span>{name}</span></div>)}</div></div></article><article className="card chart-card"><CardTitle title="Contract status" sub="Across your portfolio" action={<button className="icon-btn"><MoreHorizontal/></button>}/><div className="donut-wrap"><div className="donut"><div><strong>246</strong><span>Total</span></div></div><div className="legend"><Legend color="green" label="Active" value="192"/><Legend color="red" label="Expired" value="7"/><Legend color="gray" label="Draft" value="47"/></div></div></article><article className="card chart-card"><CardTitle title="Spend by department" sub="Year to date" action={<button className="icon-btn"><MoreHorizontal/></button>}/><div className="h-bars">{[['Engineering',72,'₹6.8L'],['Operations',58,'₹5.4L'],['Marketing',46,'₹4.1L'],['Finance',28,'₹2.2L']].map(([n,w,v]:any)=><div className="hbar" key={n}><div><span>{n}</span><b>{v}</b></div><i><em style={{width:`${w}%`}}/></i></div>)}</div></article></section><section className="card table-card"><CardTitle title="Expiring soon" sub="Contracts requiring your attention" action={<button className="text-button" onClick={()=>go('contracts')}>View all <ArrowUpRight/></button>}/><ContractTable rows={contracts.slice(0,4)}/></section></>}
function CardTitle({title,sub,action}:{title:string;sub:string;action?:React.ReactNode}){return <div className="card-title"><div><h2>{title}</h2><p>{sub}</p></div>{action}</div>}
function Legend({color,label,value}:{color:string;label:string;value:string}){return <div className="legend-row"><i className={color}/><span>{label}</span><b>{value}</b></div>}
function Vendors({go,select}:{go:(v:View)=>void;select:(v:any)=>void}){const [q,setQ]=useState('');const [rows,setRows]=useState(vendors);const addVendor=()=>{const name=window.prompt('Vendor name');if(!name?.trim())return;const code=`VND-${Math.floor(1200+Math.random()*800)}`;setRows(current=>[{code,name:name.trim(),category:'Other',email:'',country:'India',status:'Active',owner:'Priya Menon',contracts:0,value:0},...current])};const filteredRows=rows.filter(v=>v.name.toLowerCase().includes(q.toLowerCase())||v.code.toLowerCase().includes(q.toLowerCase()));return <><PageHead title="Vendors" sub="Manage your vendor relationships and performance." action={<button className="button primary" onClick={addVendor}><Plus/>Add vendor</button>}/><div className="toolbar"><label className="input-wrap"><Search/><input placeholder="Search vendors..." value={q} onChange={e=>setQ(e.target.value)}/></label><button className="filter-btn"><Filter/>All categories<ChevronDown/></button><button className="filter-btn">All status<ChevronDown/></button><span className="result-count">Showing {filteredRows.length} vendors</span></div><div className="card table-card data-table-card"><table><thead><tr><th>Vendor</th><th>Category</th><th>Contact</th><th>Owner</th><th>Contracts</th><th>Status</th><th/></tr></thead><tbody>{filteredRows.map(v=><tr key={v.code} onClick={()=>select(v)}><td><div className="vendor-cell"><span className="avatar avatar-soft">{initials(v.name)}</span><div><b>{v.name}</b><small>{v.code}</small></div></div></td><td><span className="category-pill">{v.category}</span></td><td><span className="contact-cell">{v.email}<Copy size={14}/></span></td><td>{v.owner}</td><td><b>{v.contracts}</b><small className="muted-block">{money(v.value)}</small></td><td><Status status={v.status}/></td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table><Pagination/></div></>}
function Status({status}:{status:string}){return <span className={`status ${status.toLowerCase()}`}><i/>{status}</span>}
function Pagination(){return <div className="pagination"><span>Showing <b>1–6</b> of <b>128</b></span><div><button className="page-btn"><ChevronLeft/></button><button className="page-btn current">1</button><button className="page-btn">2</button><button className="page-btn">3</button><span>...</span><button className="page-btn">12</button><button className="page-btn"><ChevronRight/></button></div></div>}
function VendorDetail({vendor,back}:{vendor:any;back:()=>void}){const [tab,setTab]=useState('Contracts');return <><div className="detail-top"><button className="back-btn" onClick={back}><ArrowLeft/>Back to vendors</button><div className="detail-actions"><button className="button secondary"><Pencil/>Edit vendor</button><button className="icon-btn danger-icon"><Trash2/></button></div></div><PageHead eyebrow="Vendors / Vendor detail" title={vendor.name} sub={`${vendor.code} · Managed by ${vendor.owner}`}/><section className="detail-grid"><article className="card info-card"><CardTitle title="Vendor information" sub="Core details and ownership" action={<button className="icon-btn"><Pencil/></button>}/><div className="info-grid">{[['Vendor code',vendor.code],['Category',vendor.category],['Contact email',vendor.email],['Country','India'],['Phone','+91 22 6789 1234'],['Owner',vendor.owner],['Created date','12 March 2024'],['Status','Active']].map(([l,v])=><div className="info-item" key={l}><span>{l}</span><b>{v}</b></div>)}</div></article><article className="card quick-card"><CardTitle title="Portfolio snapshot" sub="Vendor performance"/><div className="quick-stat"><ClipboardList/><span>Total contracts</span><b>{vendor.contracts}</b></div><div className="quick-stat"><TrendingUp/><span>Total value</span><b>{money(vendor.value)}</b></div><div className="quick-stat"><Users/><span>Departments</span><b>4</b></div><div className="mini-line"><i/><i/><i/><i/><i/><i/><i/></div></article></section><section className="card table-card"><div className="tabs">{['Departments','Contracts','Expired contracts'].map(t=><button className={tab===t?'selected':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}<button className="tab-action"><Download/>Export</button></div>{tab==='Departments'?<div className="empty-state"><Building2/><h3>No departments assigned</h3><p>Assign departments to start tracking spend and ownership.</p><button className="button secondary"><Plus/>Assign department</button></div>:<ContractTable rows={tab==='Expired contracts'?contracts.filter(c=>c.status==='Expired'):contracts.slice(0,3)}/>}</section></>}
function ContractTable({rows}:{rows:any[]}){return <div className="responsive-table"><table><thead><tr><th>Contract</th><th>Vendor</th><th>End date</th><th>Value</th><th>Days left</th><th>Status</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b className="mono">{c.id}</b><small className="muted-block">{c.freq} billing</small></td><td>{c.vendor}</td><td>{c.end}</td><td><b>{money(c.value)}</b></td><td><span className={`days ${c.days<30?'urgent':c.days<90?'soon':''}`}>{c.days<0?'Expired':`${c.days} days`}</span></td><td><Status status={c.status}/></td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></div>}
function Contracts(){const [selected,setSelected]=useState<string[]>([]);const [rows,setRows]=useState(contracts);const addContract=()=>{const vendor=window.prompt('Vendor name for this contract');if(!vendor?.trim())return;const id=`CNT-2026-${Math.floor(100+Math.random()*899)}`;setRows(current=>[{id,vendor:vendor.trim(),value:0,start:'24 Aug 2026',end:'24 Aug 2027',days:365,status:'Draft',priority:'Low',freq:'Yearly',renewal:'Pending'},...current])};return <><PageHead title="Contracts" sub="Track and manage every agreement in one place." action={<button className="button primary" onClick={addContract}><Plus/>Add contract</button>}/><div className="toolbar contract-toolbar"><label className="input-wrap"><Search/><input placeholder="Search by contract number or vendor..."/></label><button className="filter-btn">All statuses<ChevronDown/></button><button className="filter-btn">All priorities<ChevronDown/></button><button className="filter-btn"><CalendarDays/>Date range</button><button className="filter-btn"><Filter/>Filters</button></div>{selected.length>0&&<div className="bulkbar"><b>{selected.length} selected</b><button className="text-button"><Download/>Export</button><button className="text-button danger-text"><Trash2/>Delete</button></div>}<div className="card table-card data-table-card"><table><thead><tr><th><input type="checkbox" aria-label="Select all" onChange={e=>setSelected(e.target.checked?rows.map(c=>c.id):[])}/></th><th>Contract</th><th>Vendor</th><th>End date</th><th>Value</th><th>Priority</th><th>Days left</th><th>Status</th><th/></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.id]:s.filter(x=>x!==c.id))}/></td><td><b className="mono">{c.id}</b><small className="muted-block">{c.freq} billing</small></td><td><div className="vendor-cell compact"><span className="avatar avatar-soft">{initials(c.vendor)}</span><b>{c.vendor}</b></div></td><td>{c.end}</td><td><b>{money(c.value)}</b></td><td><span className={`priority ${c.priority.toLowerCase()}`}>{c.priority}</span></td><td><div className="progress-days"><i style={{width:`${Math.min(100,Math.max(4,c.days))}%`}}/><span>{c.days<0?'Expired':c.days+'d'}</span></div></td><td><Status status={c.status}/></td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table><Pagination/></div></>}
function SettingsPage(){const [saved,setSaved]=useState(false);return <><PageHead title="Settings" sub="Manage the essentials for your VendorFlow workspace."/><div className="settings-grid"><section className="card settings-card"><CardTitle title="Workspace" sub="Basic company details"/><label className="setting-field">Workspace name<input defaultValue="Acme Industries"/></label><label className="setting-field">Default country<select defaultValue="India"><option>India</option><option>United States</option><option>United Kingdom</option></select></label><label className="setting-field">Currency<select defaultValue="INR (₹)"><option>INR (₹)</option><option>USD ($)</option><option>EUR (€)</option></select></label><button className="button primary" onClick={()=>setSaved(true)}>{saved?'Saved':'Save changes'}</button></section><section className="card settings-card"><CardTitle title="Notifications" sub="Choose the reminders you receive"/><label className="setting-toggle"><input type="checkbox" defaultChecked/><span><b>Contract expiry reminders</b><small>Get notified before contracts expire.</small></span></label><label className="setting-toggle"><input type="checkbox" defaultChecked/><span><b>Weekly summary</b><small>Receive a weekly vendor portfolio summary.</small></span></label><label className="setting-toggle"><input type="checkbox"/><span><b>Activity updates</b><small>Notify me when records are changed.</small></span></label></section><section className="card settings-card"><CardTitle title="Profile" sub="Your workspace account"/><div className="profile-setting"><span className="avatar avatar-blue">PM</span><div><b>Priya Menon</b><small>procurement@acme.com</small></div></div><button className="button secondary" onClick={()=>window.alert('Profile editing will be available soon.')}>Edit profile</button></section></div></>}
function Reports(){return <><PageHead title="Reports & analytics" sub="Comprehensive insights into vendor spending and contract health." action={<button className="button secondary"><Download/>Export report<ChevronDown/></button>}/><section className="report-grid"><article className="card report-hero"><CardTitle title="Total vendor spending" sub="01 Aug – 24 Aug 2026"/><strong>₹18,50,000</strong><span className="growth"><ArrowUpRight/>12.4% vs previous period</span><div className="sparkline"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></article><article className="card report-card"><CardTitle title="Department spending" sub="Current financial year" action={<Download size={16}/>}/>{[['Engineering','₹6.8L',42],['Operations','₹5.4L',33],['Marketing','₹4.1L',25],['Finance','₹2.2L',15]].map(([n,v,w]:any)=><div className="report-row" key={n}><span>{n}</span><b>{v}</b><i><em style={{width:`${w}%`}}/></i></div>)}</article><article className="card report-card"><CardTitle title="Top vendors by value" sub="Active contracts" action={<MoreHorizontal/>}/>{vendors.slice(0,4).map(v=><div className="top-vendor" key={v.code}><span className="avatar avatar-soft">{initials(v.name)}</span><div><b>{v.name}</b><small>{v.contracts} contracts</small></div><strong>{money(v.value)}</strong></div>)}</article><article className="card report-card expiring-report"><CardTitle title="Expiring contracts" sub="Next 90 days" action={<button className="text-button">View all <ArrowUpRight/></button>}/>{contracts.slice(0,4).map(c=><div className="expiring-row" key={c.id}><div><b className="mono">{c.id}</b><small>{c.vendor}</small></div><span className={c.days<30?'urgent-text':''}>{c.days} days</span><strong>{money(c.value)}</strong></div>)}</article><article className="card report-card"><CardTitle title="Monthly spending trend" sub="Last 12 months"/><div className="trend-chart">{[38,46,40,59,50,67,55,71,63,78,74,86].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="chart-labels"><span>Sep</span><span>Mar</span><span>Aug</span></div></article><article className="card report-card"><CardTitle title="Contract health" sub="Portfolio overview"/><div className="health"><div className="donut small"><div><strong>78%</strong><span>healthy</span></div></div><div className="legend"><Legend color="green" label="Active" value="192"/><Legend color="red" label="Expired" value="7"/><Legend color="gray" label="Draft" value="47"/></div></div></article></section></>}
function Login({onLogin}:{onLogin:()=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');return <main className="login-screen"><div className="login-orb orb-one"/><div className="login-orb orb-two"/><section className="login-card"><Brand/><div className="login-heading"><h1>Welcome back</h1><p>Sign in to your VendorFlow workspace</p></div><form onSubmit={e=>{e.preventDefault();if(!email||!password)setError('Enter your email and password to continue');else onLogin()}}><label>Email address<div className="login-input"><Mail/><input type="email" value={email} onChange={e=>{setEmail(e.target.value);setError('')}} placeholder="you@company.com"/></div></label><label>Password<div className="login-input"><ShieldCheck/><input type="password" value={password} onChange={e=>{setPassword(e.target.value);setError('')}} placeholder="Enter your password"/></div></label><div className="login-options"><label className="remember"><input type="checkbox"/> Remember me</label><button type="button" className="link-button">Forgot password?</button></div>{error&&<p className="form-error">{error}</p>}<button className="button primary login-button">Sign in <ArrowUpRight/></button></form><div className="or"><span>or continue with</span></div><button className="button secondary sso-button"><span className="google-mark">G</span>Continue with SSO</button><p className="login-foot">© 2026 VendorFlow. All rights reserved.</p></section></main>}

